### ISSUE TITLE
Parser events only sent on next write()

### ISSUE THREAD

**Issue by vvo** [substack/tap-parser#24]
Every event like `assert` is only sent when the parser has received the next line.

This is somehow strange because when building tools like reporters, if a test finishes then
you get a `comment` event only when the first `assert` of the next test is parsed.

Thus resulting in things like this:

console output (tape):
![2015-06-10-152412_345x237_scrot](https://cloud.githubusercontent.com/assets/123822/8083446/e0fec27e-0f84-11e5-8b28-64f1ec8e93fd.png)

dom reporter relying on `tap-parser` events:
![2015-06-10-152422_432x168_scrot](https://cloud.githubusercontent.com/assets/123822/8083448/e23c39d2-0f84-11e5-9471-8c02bf5e568e.png)

What do you think? (this is a change from 0.7 of tap-parser where we got the events right after a `write` occured)

```js
var parser = require('./');
var p = parser();

p.on('assert', function() {
  console.log('assert!');
});

p.write('TAP version 13\n');
p.write('# beep\n');
p.write('ok 1 yeah!\n');
p.write('# boop\n');
p.write('ok 1 woohoo!\n');

// I thought I would get 'assert!' for the previous line, but
// I will only get it when something else is written to the parser
setTimeout(function() {
  p.write('\n\n');
  p.write('1..2\n');
  p.write('# tests 2\n');
  p.write('# pass 2\n');
  p.write('\n\n');
  p.write('# ok\n');
}, 10000);
```

**Comment by isaacs** [comment]
Right, that's because an assert can be more than one line.

```
not ok - this has diags
  ---
  this: is
  part: of
  the: assert
  result: object
  ...
```

**Comment by vvo** [comment]
So if I want to build something like a streaming tap parser/reporter, this current project is not my solution.
